def generate(name, spec, template_type):
    """
    generates the template corresponding to the template_type.

    Parameters
    ----------
    Name is the deployment name
    name : str
        deployment name to be used by the template. This name will be used
        to create the resource names.
    spec : dict
        The properties of the deployment (specifications) passed from the deployment_config's 
        `spec` section.
    template_type: str
        The type of template that is to be generated by the operator. Available ones are [terraform, cloudformation]
           
    Returns
    -------
    generated_path : str
        The path for the generated template.
    """
    generated_path = ""
    return generated_path
